#mysql??
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis??
mybatis:
  configuration:
    #??
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #???????
    map-underscore-to-camel-case: true
